---
version: "0.1"
matrix:
  os: [win]
  methods: ['tests/scenario.spec.js']
runson: ${matrix.os}
pre:
  - npm install
  - npx playwright install
cacheKey: '{{ checksum "package-lock.json" }}'
cacheDirectories:
  - node_modules
testSuites:
  - npx playwright test $methods

jobLabel: [playwright-VanillaJS, win, matrix] 